defaults:
  - _self_
  - dataset: test_for_sybil
  - classifier: nlst_sybil_ensemble


exp:
  seed: 42
  batch_size: 1
  split_name: "test" # Ignored

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1