_target_: torch.utils.data.DataLoader
dataset: 
  _target_: dataset.TestCTDataset
  name: testct
  split: ${exp.split_name}
  path_data: data/ct
batch_size: ${exp.batch_size}
prefetch_factor: null
pin_memory: false
num_workers: 0